#include "pch.h"
#include "NamesMap.h"

static const std::map<std::string, std::string> names_map = {
    {"Aquadome", "Underwater_P"},
    {"Beckwith Park", "Park_P"},
    {"Beckwith Park (Midnight)", "Park_Night_P"},
    {"Beckwith Park (Snowy)", "Park_Snowy_P"},
    {"Beckwith Park (Stormy)", "Park_Rainy_P"},
    {"Beckwith Park (Batman)", "Park_bman_p"},
    {"Champions Field", "cs_p"},
    {"Champions Field (Day)", "cs_day_p"},
    {"Champions Field (NFL)", "bb_p"},
    {"Champions Field (Nike)", "swoosh_p"},
    {"DFH Stadium", "Stadium_P"},
    {"DFH Stadium (Day)", "stadium_day_p"},
    {"DFH Stadium (Circuit)", "Stadium_Race_Day_p"},
    {"DFH Stadium (Snowy)", "Stadium_Winter_P"},
    {"DFH Stadium (Stormy)", "Stadium_Foggy_P"},
    {"Deadeye Canyon", "outlaw_p"},
    {"Farmstead", "farm_p"},
    {"Farmstead (Night)", "Farm_Night_P"},
    {"Farmstead (Spooky)", "Farm_HW_P"},
    {"Forbidden Temple", "CHN_Stadium_P"},
    {"Forbidden Temple (Day)", "CHN_Stadium_Day_P"},
    {"Forbidden Temple (Fire & Ice)", "FNI_Stadium_P"},
    {"Mannfield", "EuroStadium_P"},
    {"Mannfield (Stormy)", "EuroStadium_Rainy_P"},
    {"Mannfield (Night)", "EuroStadium_Night_P"},
    {"Mannfield (Snowy)", "EuroStadium_snownight_p"},
    {"Neo Tokyo", "NeoTokyo_Standard_P"},
    {"Neo Tokyo (Comic)", "NeoTokyo_Toon_p"},
    {"Neon Fields", "music_p"},
    {"Rivals Arena", "cs_hw_p"},
    {"Salty Shores", "beach_P"},
    {"Salty Shores (Night)", "beach_night_p"},
    {"Sovereign Heights", "street_p"},
    {"Urban Central", "TrainStation_P"},
    {"Urban Central (Haunted)", "Haunted_TrainStation_P"},
    {"Urban Central (Dawn)", "TrainStation_Dawn_P"},
    {"Urban Central (Night)", "TrainStation_Night_P"},
    {"Utopia Coliseum", "UtopiaStadium_P"},
    {"Utopia Coliseum (Dusk)", "UtopiaStadium_Dusk_P"},
    {"Utopia Coliseum (Gilded)", "UtopiaStadium_Lux_P"},
    {"Utopia Coliseum (Snowy)", "UtopiaStadium_Snow_P"},
    {"Wasteland", "wasteland_s_p"},
    {"Wasteland (Night)", "wasteland_Night_S_P"}
};

static const std::vector<std::string> friendly_map_names = {
    {"Aquadome"},
    {"Beckwith Park"},
    {"Beckwith Park (Midnight)"},
    {"Beckwith Park (Snowy)"},
    {"Beckwith Park (Stormy)"},
    {"Beckwith Park (Batman)"},
    {"Champions Field"},
    {"Champions Field (Day)"},
    {"Champions Field (NFL)"},
    {"Champions Field (Nike)"},
    {"DFH Stadium"},
    {"DFH Stadium (Day)"},
    {"DFH Stadium (Circuit)"},
    {"DFH Stadium (Snowy)"},
    {"DFH Stadium (Stormy)"},
    {"Deadeye Canyon"},
    {"Farmstead"},
    {"Farmstead (Night)"},
    {"Farmstead (Spooky)"},
    {"Forbidden Temple"},
    {"Forbidden Temple (Day)"},
    {"Forbidden Temple (Fire & Ice)"},
    {"Mannfield"},
    {"Mannfield (Stormy)"},
    {"Mannfield (Night)"},
    {"Mannfield (Snowy)"},
    {"Neo Tokyo"},
    {"Neo Tokyo (Comic)"},
    {"Neon Fields"},
    {"Rivals Arena"},
    {"Salty Shores"},
    {"Salty Shores (Night)"},
    {"Sovereign Heights"},
    {"Urban Central"},
    {"Urban Central (Haunted)"},
    {"Urban Central (Dawn)"},
    {"Urban Central (Night)"},
    {"Utopia Coliseum"},
    {"Utopia Coliseum (Dusk)"},
    {"Utopia Coliseum (Gilded)"},
    {"Utopia Coliseum (Snowy)"},
    {"Wasteland"},
    {"Wasteland (Night)"}
};

static const std::vector<std::string> internal_map_names = {
    {"Underwater_P"},
    {"Park_P"},
    {"Park_Night_P"},
    {"Park_Snowy_P"},
    {"Park_Rainy_P"},
    {"Park_bman_p"},
    {"cs_p"},
    {"cs_day_p"},
    {"bb_p"},
    {"swoosh_p"},
    {"Stadium_P"},
    {"stadium_day_p"},
    {"Stadium_Race_Day_p"},
    {"Stadium_Winter_P"},
    {"Stadium_Foggy_P"},
    {"outlaw_p"},
    {"farm_p"},
    {"Farm_Night_P"},
    {"Farm_HW_P"},
    {"CHN_Stadium_P"},
    {"CHN_Stadium_Day_P"},
    {"FNI_Stadium_P"},
    {"EuroStadium_P"},
    {"EuroStadium_Rainy_P"},
    {"EuroStadium_Night_P"},
    {"EuroStadium_snownight_p"},
    {"NeoTokyo_Standard_P"},
    {"NeoTokyo_Toon_p"},
    {"music_p"},
    {"cs_hw_p"},
    {"beach_P"},
    {"beach_night_p"},
    {"street_p"},
    {"TrainStation_P"},
    {"Haunted_TrainStation_P"},
    {"TrainStation_Dawn_P"},
    {"TrainStation_Night_P"},
    {"UtopiaStadium_P"},
    {"UtopiaStadium_Dusk_P"},
    {"UtopiaStadium_Lux_P"},
    {"UtopiaStadium_Snow_P"},
    {"wasteland_s_p"},
    {"wasteland_Night_S_P"}
};

static const std::map<std::string, Region> region_map = {
    {"US-East", Region::USE},
    {"Europe", Region::EU},
    {"US-West", Region::USW},
    {"Asia-SE Mainland", Region::ASC},
    {"Asia-SE Maritime", Region::ASM},
    {"Asia-East", Region::JPN},
    {"Middle-East", Region::ME},
    {"Oceania", Region::OCE},
    {"South Africa", Region::SAF},
    {"South America", Region::SAM},
    {"India", Region::IND}
};

static const std::vector<std::string> region_friendly_names = {
    "US-East",
    "Europe",
    "US-West", 
    "Asia-SE Mainland",
    "Asia-SE Maritime",
    "Asia-East",
    "Middle-East",
    "Oceania",
    "South Africa",
    "South America",
    "India",
};
